# --- Build stage ---
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download
RUN go mod verify

# Copy the rest of the source code
COPY . .

# Install swag CLI
RUN go install github.com/swaggo/swag/cmd/swag@latest
ENV PATH="/go/bin:${PATH}"

# Generate Swagger docs
RUN swag init -g cmd/server/main.go

# Build the Go app
RUN go build -o bin/app ./cmd/server/main.go

# --- Run stage ---
FROM alpine:3.19

WORKDIR /app

# Copy migration files if needed
COPY --from=builder /app/migrations ./migrations

# Copy the built binary from builder
COPY --from=builder /app/bin/app ./bin/app

EXPOSE 3000

CMD ["./bin/app"]